[build]
  publish = "build/web"
  command = "git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter && export PATH=$PATH:$HOME/flutter/bin && flutter doctor && flutter build web --release --dart-define=SUPABASE_PUBLISHABLE_KEY=$SUPABASE_PUBLISHABLE_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
