[build]
  publish = "build/web"
  command = "bash build.sh"
  environment = { SECRETS_SCAN_OMIT_KEYS = "SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
