[build]
  publish = "build/web"
  command = "flutter build web --release --dart-define=SUPABASE_PUBLISHABLE_KEY=$SUPABASE_PUBLISHABLE_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
