import 'package:flutter/material.dart';
import '../../../core/models/booking.dart';
import '../../../shared/theme/app_colors.dart';
import '../../../shared/theme/app_text_styles.dart';
import '../../../shared/widgets/aeromed_card.dart';
import '../../../shared/widgets/aeromed_page.dart';

class BookingHistoryPage extends StatefulWidget {
  const BookingHistoryPage({super.key, required this.bookings});
  final List<Booking> bookings;
  @override State<BookingHistoryPage> createState()=>_BookingHistoryPageState();
}
class _BookingHistoryPageState extends State<BookingHistoryPage>{String q='';@override Widget build(BuildContext context){final history=widget.bookings.where((b)=>b.isCompleted||b.isCancelled).where((b){final s=q.toLowerCase();return s.isEmpty||b.id.toLowerCase().contains(s)||b.patientName.toLowerCase().contains(s)||b.destination.toLowerCase().contains(s);}).toList();final completed=widget.bookings.where((b)=>b.isCompleted).length;final cancelled=widget.bookings.where((b)=>b.isCancelled).length;return AeroMedPage(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const AeroMedPageHeader(title:'Booking History',subtitle:'Completed and cancelled ambulance cases, invoices and transfer records.'),const SizedBox(height:16),TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search_rounded),labelText:'Search Booking ID, patient or destination'),onChanged:(v)=>setState(()=>q=v)),const SizedBox(height:14),Row(children:[Expanded(child:_stat('Completed','$completed')),const SizedBox(width:10),Expanded(child:_stat('Cancelled','$cancelled')),]),const SizedBox(height:16),if(history.isEmpty)const AeroMedCard(child:Padding(padding:EdgeInsets.all(20),child:Center(child:Text('No historical bookings found.')))),...history.map((b)=>Padding(padding:const EdgeInsets.only(bottom:10),child:_tile(context,b))) ]));}
Widget _stat(String l,String v)=>AeroMedCard(shadow:false,padding:const EdgeInsets.all(14),child:Column(children:[Text(v,style:AppTextStyles.pageTitle.copyWith(fontSize:20)),Text(l,style:AppTextStyles.caption)]));
Widget _tile(BuildContext c,Booking b){final done=b.isCompleted;return AeroMedCard(shadow:false,onTap:()=>_details(c,b),child:Row(children:[Container(width:42,height:42,decoration:BoxDecoration(color:done?AppColors.successSoft:AppColors.warningSoft,borderRadius:BorderRadius.circular(12)),child:Icon(done?Icons.check_rounded:Icons.close_rounded,color:done?AppColors.success:AppColors.warning)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(b.id,style:AppTextStyles.bodyStrong),Text('${b.patientName} • ${b.date} • ${b.ambulanceType}',style:AppTextStyles.supporting),Text('${b.pickup} → ${b.destination}',maxLines:1,overflow:TextOverflow.ellipsis,style:AppTextStyles.supporting)])),Text(b.formattedAmount,style:AppTextStyles.cardTitle)]));}
void _details(BuildContext c,Booking b)=>showDialog(context:c,builder:(_)=>AlertDialog(title:Text(b.id),content:SingleChildScrollView(child:Text('Status: ${b.customerStatusLabel}\nPatient: ${b.patientName}\nCondition: ${b.currentCondition}\n\n${b.pickup} → ${b.destination}\n${b.date} • ${b.time}\nAmbulance: ${b.ambulanceType}\nVehicle: ${b.vehicleNumber}\n\nMedical requirements: ${[if(b.oxygenRequired)'Oxygen',if(b.icuRequired)'ICU',if(b.ventilatorRequired)'Ventilator',if(b.doctorRequired)'Doctor',if(b.emtRequired)'EMT',if(b.stretcherRequired)'Stretcher',if(b.wheelchairRequired)'Wheelchair'].join(', ')}\n\nAmount: ${b.formattedAmount}\nPayment: ${b.paymentStatus}${b.cancellationReason.isNotEmpty?'\nCancellation reason: ${b.cancellationReason}':''}')),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]));}
